### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by 3377** [ImYrS/aliyun-auto-signin#25]
[root@localhost aliyun-auto-signin-main]# python app.py
Traceback (most recent call last):
  File "/py/aliyun-auto-signin-main/app.py", line 19, in <module>
    from modules import dingtalk, serverchan, pushdeer, telegram, pushplus, smtp
  File "/py/aliyun-auto-signin-main/modules/dingtalk.py", line 64, in <module>
    config: Optional[ConfigObj | dict],
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by ImYrS** [comment]
@3377 检查 python 版本

**Comment by 3377** [comment]
@ImYrS 已经升级到3.11.0，新的报错。。。
[root@localhost aliyun-auto-signin-main]# python -V
Python 3.11.0
[root@localhost aliyun-auto-signin-main]# python app.py
Traceback (most recent call last):
  File "/usr/local/python3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 692, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
    return conn or self._new_conn()
                   ^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1011, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3.11/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/python3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='auth.aliyundrive.com', port=443): Max retries exceeded with url: /v2/account/token (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/py/aliyun-auto-signin-main/app.py", line 259, in <module>
    main()
  File "/py/aliyun-auto-signin-main/app.py", line 238, in main
    data = get_access_token(user)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/py/aliyun-auto-signin-main/app.py", line 29, in get_access_token
    data = requests.post(
           ^^^^^^^^^^^^^^
  File "/usr/local/python3.11/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='auth.aliyundrive.com', port=443): Max retries exceeded with url: /v2/account/token (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Comment by ImYrS** [comment]
@3377 这是环境问题, 可能是编译的时候 SSL 配置问题, 非代码自己解决, 解决不了用 github action
