### ISSUE TITLE
报错TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by luomo-pro** [ImYrS/aliyun-auto-signin#28]
使用的是Python 3.8.10，运行报错如下：
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    import github
  File "/ali/github.py", line 24, in <module>
    def get_pub_key(repos: str, token: str) -> tuple[str, int]:
TypeError: 'type' object is not subscriptable

**Comment by ImYrS** [comment]
python >= 3.10
