### ISSUE TITLE
Action 在 __sign_in() 函数发生网络错误

### ISSUE THREAD

**Issue by cike-567** [ImYrS/aliyun-auto-signin#33]
昨天能正常运行，今天就不能了。

Run ImYrS/aliyun-auto-signin@main
Run actions/checkout@v3
Syncing repository: cike-567/aliyun-auto-signin
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/eb4f64e7-8d29-45b6-94a7-a0d096e3d9f1' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/aliyun-auto-signin/aliyun-auto-signin
Deleting the contents of '/home/runner/work/aliyun-auto-signin/aliyun-auto-signin'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
Checking out the ref
/usr/bin/git log -1 --format='%H'
'800d11e9742dfaa0da3ccb7baf9879ee160508ea'
Run actions/setup-python@v4
Installed versions
Run pozetroninc/github-action-get-latest-release@master
Run wget https://github.com/ImYrS/aliyun-auto-signin/archive/refs/tags/v1.4.2.zip -O release.zip
--2023-03-20 01:52:57--  https://github.com/ImYrS/aliyun-auto-signin/archive/refs/tags/v1.4.2.zip
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/ImYrS/aliyun-auto-signin/zip/refs/tags/v1.4.2 [following]
--2023-03-20 01:52:58--  https://codeload.github.com/ImYrS/aliyun-auto-signin/zip/refs/tags/v1.4.2
Resolving codeload.github.com (codeload.github.com)... 192.30.255.121
Connecting to codeload.github.com (codeload.github.com)|192.30.255.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32383 (32K) [application/zip]
Saving to: ‘release.zip’

     0K .......... .......... .......... .                    100% 1.49M=0.02s

2023-03-20 01:52:58 (1.49 MB/s) - ‘release.zip’ saved [32383/32383]

Archive:  release.zip
c94c25834e1f14a2468302800bb44970fef5dfe2
   creating: release/aliyun-auto-signin-1.4.2/
  inflating: release/aliyun-auto-signin-1.4.2/.gitignore  
  inflating: release/aliyun-auto-signin-1.4.2/How-To-Use-Action.md  
  inflating: release/aliyun-auto-signin-1.4.2/LICENSE  
  inflating: release/aliyun-auto-signin-1.4.2/README.md  
  inflating: release/aliyun-auto-signin-1.4.2/action.yml  
  inflating: release/aliyun-auto-signin-1.4.2/app.py  
  inflating: release/aliyun-auto-signin-1.4.2/example.config.ini  
  inflating: release/aliyun-auto-signin-1.4.2/github.py  
   creating: release/aliyun-auto-signin-1.4.2/modules/
  inflating: release/aliyun-auto-signin-1.4.2/modules/dingtalk.py  
  inflating: release/aliyun-auto-signin-1.4.2/modules/feishu.py  
  inflating: release/aliyun-auto-signin-1.4.2/modules/pushdeer.py  
  inflating: release/aliyun-auto-signin-1.4.2/modules/pushplus.py  
  inflating: release/aliyun-auto-signin-1.4.2/modules/serverchan.py  
  inflating: release/aliyun-auto-signin-1.4.2/modules/smtp.py  
  inflating: release/aliyun-auto-signin-1.4.2/modules/telegram.py  
 extracting: release/aliyun-auto-signin-1.4.2/requirements.txt  
Run cd release
Collecting requests~=2.28.2
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 1.4 MB/s eta 0:00:00
Collecting configobj~=5.0.8
  Downloading configobj-5.0.8-py2.py3-none-any.whl (36 kB)
Collecting pynacl~=1.5.0
  Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 856.7/856.7 kB 24.1 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 37.8 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 kB 32.3 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 30.1 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 12.7 MB/s eta 0:00:00
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting cffi>=1.4.1
  Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 kB 56.3 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 27.9 MB/s eta 0:00:00
Installing collected packages: urllib3, six, pycparser, idna, charset-normalizer, certifi, requests, configobj, cffi, pynacl
Successfully installed certifi-2022.12.7 cffi-1.15.1 charset-normalizer-3.1.0 configobj-5.0.8 idna-3.4 pycparser-2.21 pynacl-1.5.0 requests-2.28.2 six-1.16.0 urllib3-1.26.15
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/aliyun-auto-signin/aliyun-auto-signin/release/aliyun-auto-signin-1.4.2/app.py", line 334, in <module>
    main()
  File "/home/runner/work/aliyun-auto-signin/aliyun-auto-signin/release/aliyun-auto-signin-1.4.2/app.py", line 310, in main
    result = SignIn(config=config, refresh_token=user).run()
  File "/home/runner/work/aliyun-auto-signin/aliyun-auto-signin/release/aliyun-auto-signin-1.4.2/app.py", line 166, in run
    self.__sign_in()
  File "/home/runner/work/aliyun-auto-signin/aliyun-auto-signin/release/aliyun-auto-signin-1.4.2/app.py", line 94, in __sign_in
    data = requests.post(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Error: Process completed with exit code 1.

**Comment by ImYrS** [comment]
疑似网络问题, 手动运行重试一下

**Comment by cike-567** [comment]
这个是手动运行过的日志

**Comment by ImYrS** [comment]
看起来就是网络问题, 多试几次看看结果. 我刚刚测试运行没问题

**Comment by cike-567** [comment]
跑了几次，成功了一次

**Comment by ImYrS** [comment]
暂时无法复现错误

**Comment by ImYrS** [comment]
@cike-567 该错误是否持续存在?

**Comment by cike-567** [comment]
今天未出现

**Comment by ImYrS** [comment]
> 今天未出现

好的, 那应该就是临时的网络问题. 这几天会发小版本更新, 加了网络错误自动重试功能
