### ISSUE TITLE
最新版运行报错了

### ISSUE THREAD

**Issue by nhddhr** [ImYrS/aliyun-auto-signin#4]
2023-02-12 12:54:46,483 - app.py:184 - INFO: access_token 已过期, 正在更新...
Traceback (most recent call last):
  File "/ql/data/scripts/ImYrS_aliyun-auto-signin_main/app.py", line 202, in <module>
    main()
  File "/ql/data/scripts/ImYrS_aliyun-auto-signin_main/app.py", line 193, in main
    config.write()
  File "/usr/local/lib/python3.10/site-packages/configobj/__init__.py", line 2117, in write
    output_bytes = output.encode(self.encoding or
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-21: ordinal not in range(128)

**Comment by ImYrS** [comment]
重新复制 example.config.ini 填写配置试试

**Comment by nhddhr** [comment]
都试过了，就是重新复制 example.config.ini 填写配置，还是报

**Comment by exlulu** [comment]
同样错误，前一版正常，看提示和查了一下貌似和编码有关，但是试过一些查到的方法更改编码，不过还是不行

**Comment by exlulu** [comment]
删除config.ini里面所有中文即可

**Comment by nhddhr** [comment]
> 删除config.ini里面所有中文即可

......厉害

**Comment by ImYrS** [comment]
configObj 读取编码问题, 已在 [b27336](https://github.com/ImYrS/aliyun-auto-signin/commit/b273365778e3c38620726f8ebc00172c5dcfda4b) 修复
