### ISSUE TITLE
Github Action定时任务出错

### ISSUE THREAD

**Issue by Carlos920** [ImYrS/aliyun-auto-signin#45]
```shell
Successfully installed certifi-2022.12.7 cffi-1.15.1 charset-normalizer-3.1.0 configobj-5.0.8 idna-3.4 pycparser-2.21 pynacl-1.5.0 requests-2.28.2 six-1.16.0 urllib3-1.26.15
Traceback (most recent call last):
  File "/home/runner/work/Actions/Actions/release/aliyun-auto-signin-1.4.6/app.py", line 365, in <module>
    main()
  File "/home/runner/work/Actions/Actions/release/aliyun-auto-signin-1.4.6/app.py", line 342, in main
    results.append(signin.run())
  File "/home/runner/work/Actions/Actions/release/aliyun-auto-signin-1.4.6/app.py", line 190, in run
    self.__sign_in()
  File "/home/runner/work/Actions/Actions/release/aliyun-auto-signin-1.4.6/app.py", line 139, in __sign_in
    if not current_day['isReward']
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.
```

**Comment by jzx765** [comment]
![image](https://user-images.githubusercontent.com/56497479/228989637-f8a02494-13bb-4a02-8632-1d7250b6af38.png)
我也是，今天起来一看，邮件提示运行错误了

**Comment by 237686270** [comment]
一样，我也是我设定是凌晨两点，没有运行，报错了

**Comment by Zxr112553438** [comment]
![image](https://user-images.githubusercontent.com/93114244/229014632-25c94668-6846-4e52-b5bd-6577027d896e.png)
也一样，报错，但是好像签到又做了

**Comment by Carlos920** [comment]
> ![image](https://user-images.githubusercontent.com/93114244/229014632-25c94668-6846-4e52-b5bd-6577027d896e.png) 也一样，报错，但是好像签到又做了

是的，似乎是推送跪了

**Comment by jzx765** [comment]
我是没做，全跪了

**Comment by ImYrS** [comment]
稍安勿躁，这个问题昨晚已经定位并解决。尚未经过完整测试，还没发布 release。一般情况下，不影响领取奖励。

**Comment by ImYrS** [comment]
应在 [v1.5.0](https://github.com/ImYrS/aliyun-auto-signin/releases/tag/v1.5.0) 修复
